on:
  push:
    branches: [main]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/configure-pages@v3
      - uses: docker/setup-buildx-action@v3

      - name: Build
        env:
          MAPTILER_API_KEY: ${{ secrets.MAPTILER_API_KEY }}
        run: docker build -t area-selector --build-arg "MAPTILER_API_KEY=$MAPTILER_API_KEY" .

      - name: Copy generated files
        run: docker cp $(docker create area-selector):/build/dist ./dist

      - uses: actions/upload-pages-artifact@v2
        with:
          path: dist

  deploy:
    name: Deploy
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
    runs-on: ubuntu-latest
    needs: build
    permissions:
      pages: write # to deploy to Pages
      id-token: write # to verify the deployment originates from an appropriate source
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
